name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Global permissions (safe to keep)
permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  snapshot:
    runs-on: self-hosted
    needs: build

    # Explicit permissions for this job
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Submit Maven Dependency Tree
        uses: advanced-security/maven-dependency-submission-action@v1
